ERROR 2022-09-05 14:41:55,581 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 384 (FILENAME gadget)
ERROR 2022-09-05 18:49:37,178 :  Reverse for 'unknownControllerRemove' not found. 'unknownControllerRemove' is not a valid view function or pattern name. from function history in line no. 304 (FILENAME views)
ERROR 2022-09-07 10:19:42,499 :  Error: TickerDetails matching query does not exist. from function detail in line no. 328 (FILENAME views)
ERROR 2022-09-07 10:19:43,030 :  Error: TickerDetails matching query does not exist. from function detail in line no. 328 (FILENAME views)
ERROR 2022-09-08 11:07:25,145 :  QuerySet indices must be integers or slices, not str. from function configApi in line no. 759 (FILENAME views)
ERROR 2022-09-08 11:07:40,358 :  get() returned more than one TickerHistory -- it returned 2! from function configApi in line no. 759 (FILENAME views)
ERROR 2022-09-08 11:07:46,959 :  int() argument must be a string, a bytes-like object or a number, not 'NoneType' from function configApi in line no. 759 (FILENAME views)
ERROR 2022-09-08 11:08:11,478 :  int() argument must be a string, a bytes-like object or a number, not 'NoneType' from function configApi in line no. 759 (FILENAME views)
ERROR 2022-09-08 11:34:42,321 :  '2022-09-08 11:34:41' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 11:38:27,272 :  int() argument must be a string, a bytes-like object or a number, not 'NoneType' from function configApi in line no. 759 (FILENAME views)
ERROR 2022-09-08 13:35:04,114 :  '2022-09-08 13:35:03' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 14:25:09,866 :  '2022-09-08 14:25:09' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 14:48:35,437 :  '2022-09-08 14:48:35' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 14:49:52,626 :  '2022-09-08 14:49:52' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 14:50:40,040 :  '2022-09-08 14:50:39' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 14:51:42,696 :  '2022-09-08 14:51:42' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 14:52:25,440 :  '2022-09-08 14:52:25' is not in list from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 15:16:09,468 :  QuerySet indices must be integers or slices, not str. from function configApi in line no. 761 (FILENAME views)
ERROR 2022-09-08 15:18:33,956 :  QuerySet indices must be integers or slices, not str. from function configApi in line no. 761 (FILENAME views)
ERROR 2022-09-08 15:32:00,254 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:32:00,256 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:34:00,220 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:34:00,221 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:37:00,204 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:37:00,205 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:37:00,216 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:37:00,218 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:39:00,245 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:39:00,248 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:39:16,581 :  Object of type QuerySet is not JSON serializable from function schedule_tasks in line no. 106 (FILENAME ticker_schedules)
ERROR 2022-09-08 15:42:00,224 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:42:00,227 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:42:04,637 :  Object of type QuerySet is not JSON serializable from function schedule_tasks in line no. 107 (FILENAME ticker_schedules)
ERROR 2022-09-08 15:46:23,423 :  Object of type QuerySet is not JSON serializable from function schedule_tasks in line no. 107 (FILENAME ticker_schedules)
ERROR 2022-09-08 15:47:00,204 :  Error while execution of task: 'int' object has no attribute 'get' from function callticker in line no. 44 (FILENAME tasks)
ERROR 2022-09-08 15:47:00,206 :  'int' object has no attribute 'get' from function initial_data in line no. 38 (FILENAME rundecklog)
ERROR 2022-09-08 15:48:17,376 :  Object of type QuerySet is not JSON serializable from function schedule_tasks in line no. 107 (FILENAME ticker_schedules)
ERROR 2022-09-08 15:49:54,082 :  Object of type QuerySet is not JSON serializable from function schedule_tasks in line no. 107 (FILENAME ticker_schedules)
ERROR 2022-09-08 16:03:16,670 :  Object of type QuerySet is not JSON serializable from function schedule_tasks in line no. 107 (FILENAME ticker_schedules)
ERROR 2022-09-08 16:19:52,557 :  Unable to update: name 'perRoom' is not defined from function datagetter in line no. 409 (FILENAME gadget)
ERROR 2022-09-08 16:44:48,194 :  string indices must be integers from function schedule_tasks in line no. 108 (FILENAME ticker_schedules)
ERROR 2022-09-08 18:10:52,021 :  Error: TickerDetails matching query does not exist. from function detail in line no. 330 (FILENAME views)
ERROR 2022-09-09 10:28:34,054 :  ID 55 not found from function isDelete in line no. 492 (FILENAME views)
ERROR 2022-09-09 14:14:47,311 :  get() returned more than one RundeckLog -- it returned 2! from function tvIpadStatus in line no. 1083 (FILENAME views)
ERROR 2022-09-09 14:14:50,260 :  get() returned more than one RundeckLog -- it returned 2! from function tvIpadStatus in line no. 1083 (FILENAME views)
ERROR 2022-09-09 14:15:02,838 :  get() returned more than one RundeckLog -- it returned 2! from function tvIpadStatus in line no. 1083 (FILENAME views)
ERROR 2022-09-09 14:54:11,827 :  string indices must be integers from function schedulingticker in line no. 157 (FILENAME ticker_schedules)
ERROR 2022-09-09 14:55:46,214 :  string indices must be integers from function schedulingticker in line no. 160 (FILENAME ticker_schedules)
ERROR 2022-09-09 14:57:47,590 :  string indices must be integers from function schedulingticker in line no. 159 (FILENAME ticker_schedules)
ERROR 2022-09-09 14:59:24,208 :  'time_interval' from function initial_data in line no. 39 (FILENAME rundecklog)
ERROR 2022-09-09 14:59:44,702 :  'time_interval' from function initial_data in line no. 39 (FILENAME rundecklog)
ERROR 2022-09-09 15:02:10,111 :  'str' object has no attribute 'read' from function schedulingticker in line no. 160 (FILENAME ticker_schedules)
ERROR 2022-09-09 15:09:51,024 :  'second' is an invalid keyword argument for __new__() from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-09 15:10:52,725 :  Field 'time_interval' expected a number but got datetime.datetime(2022, 9, 9, 15, 11, 52, 720497). from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-09 15:23:13,531 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-09 15:23:35,400 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-09 15:34:03,883 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-09 15:36:12,149 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-09 16:02:52,120 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:02:57,665 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:03:03,546 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:14:34,542 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:14:40,334 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:14:46,417 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:14:52,429 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:14:58,521 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:05,402 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:11,431 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:17,526 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:24,384 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:30,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:36,417 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:42,403 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:48,379 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:15:54,420 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:00,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:06,404 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:12,390 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:18,396 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:24,394 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:31,659 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:37,390 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:43,453 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:49,381 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:16:55,387 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:01,390 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:07,399 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:14,054 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:20,388 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:26,377 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:32,412 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:38,409 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:44,445 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 16:17:50,401 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:11:57,895 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:06,827 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:12,491 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:18,153 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:23,824 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:30,473 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:36,067 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:41,618 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:47,475 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:53,428 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:12:59,409 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:06,469 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:13,854 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:20,391 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:29,422 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:35,445 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:41,384 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:47,402 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:53,391 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:13:59,459 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:05,433 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:12,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:18,423 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:24,429 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:30,412 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:36,419 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:43,937 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:50,413 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:14:56,411 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:03,765 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:10,400 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:16,400 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:22,434 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:29,715 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:36,389 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:42,397 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:48,413 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:15:54,436 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:00,399 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:06,390 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:12,394 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:18,408 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:24,413 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:30,393 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:36,395 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:42,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:48,423 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:16:54,436 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:00,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:06,427 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:12,400 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:18,384 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:24,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:30,426 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:36,383 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:42,418 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:48,395 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:17:54,451 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:00,396 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:06,473 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:12,406 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:18,406 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:24,400 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:30,412 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:36,391 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:42,394 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:48,395 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:18:54,408 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:00,417 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:06,408 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:12,400 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:18,399 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:24,409 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:30,400 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:36,413 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:42,425 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:48,412 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:19:54,440 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:00,421 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:06,417 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:12,397 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:18,424 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:24,415 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:30,851 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:37,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:43,408 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:49,407 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:20:55,404 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:01,414 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:07,411 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:13,868 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:20,432 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:26,392 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:32,411 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:38,414 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:44,444 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:50,427 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-09 17:21:56,872 :  '>=' not supported between instances of 'datetime.datetime' and 'NoneType' from function rundeck_update in line no. 73 (FILENAME rundecklog)
ERROR 2022-09-12 12:10:14,062 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-12 12:46:14,197 :  Error: Could not parse the remainder: '{item.ticker_id' from '{item.ticker_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 12:52:17,430 :  Error: Could not parse the remainder: '{'ticker_id':item.ticker_id,' from '{'ticker_id':item.ticker_id,' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 12:54:29,343 :  Reverse for 'detail' with arguments '(213,)' not found. 1 pattern(s) tried: ['ticker/detail/(?P<id>[^/]+)/(?P<ids>[^/]+)$'] from function active in line no. 263 (FILENAME views)
ERROR 2022-09-12 12:54:33,615 :  Reverse for 'detail' with arguments '(213,)' not found. 1 pattern(s) tried: ['ticker/detail/(?P<id>[^/]+)/(?P<ids>[^/]+)$'] from function active in line no. 263 (FILENAME views)
ERROR 2022-09-12 12:54:49,069 :  Reverse for 'detail' with arguments '(213,)' not found. 1 pattern(s) tried: ['ticker/detail/(?P<id>[^/]+)/(?P<ids>[^/]+)$'] from function active in line no. 263 (FILENAME views)
ERROR 2022-09-12 13:50:19,535 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-12 13:50:25,118 :  get() returned more than one RundeckLog -- it returned 2! from function tvIpadStatus in line no. 1133 (FILENAME views)
ERROR 2022-09-12 14:38:27,990 :  Error: Reverse for 'abort' with arguments '(214, 954)' not found. 1 pattern(s) tried: ['ticker/abort/(?P<id>[^/]+)$'] from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 14:56:24,143 :  Error: Reverse for 'abort' with arguments '(216, 959)' not found. 1 pattern(s) tried: ['ticker/abort/(?P<id>[^/]+)$'] from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 15:41:36,053 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-12 15:41:42,934 :  get() returned more than one RundeckLog -- it returned 2! from function tvIpadStatus in line no. 1136 (FILENAME views)
ERROR 2022-09-12 16:06:26,018 :  Error: Could not parse the remainder: '{item.ticker_id}' from '{item.ticker_id}' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:07:24,232 :  Error: Could not parse the remainder: 'ticker_id":item.ticker_id}"' from '"{"ticker_id":item.ticker_id}"' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:09:15,494 :  Error: Could not parse the remainder: 'ticker_id":item.ticker_id, "randack_id":item.rundeck_id}"' from '"{"ticker_id":item.ticker_id, "randack_id":item.rundeck_id}"' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:10:11,866 :  Error: Could not parse the remainder: 'ticker_id":{{item.ticker_id}}, "randack_id":{{item.rundeck_id}}}"' from '"{"ticker_id":{{item.ticker_id}}, "randack_id":{{item.rundeck_id}}}"' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:11:25,791 :  Error: Could not parse the remainder: '+item.rundeck_id' from 'item.ticker_id+item.rundeck_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:12:12,904 :  Error: Could not parse the remainder: '&item.rundeck_id' from 'item.ticker_id&item.rundeck_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:12:22,163 :  Error: Could not parse the remainder: '&item.rundeck_id' from 'item.ticker_id&item.rundeck_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:12:28,352 :  Error: Could not parse the remainder: '&item.rundeck_id' from 'item.ticker_id&item.rundeck_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:12:34,105 :  Error: Could not parse the remainder: '&' from '&' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 16:12:38,081 :  Error: Could not parse the remainder: '&' from '&' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:05:42,180 :  Error: Could not parse the remainder: '{{item.ticker_id}}&{{item.rundeck_id}}' from '{{item.ticker_id}}&{{item.rundeck_id}}' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:06:12,013 :  Error: Reverse for '' not found. '' is not a valid view function or pattern name. from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:07:01,435 :  Error: Could not parse the remainder: '{{item.ticker_id' from '{{item.ticker_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:07:26,594 :  Error: Reverse for '' not found. '' is not a valid view function or pattern name. from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:07:47,458 :  Error: Reverse for '' not found. '' is not a valid view function or pattern name. from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:08:16,349 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-12 17:09:29,233 :  Error: Could not parse the remainder: '{{item.ticker_id}}{{item.rundeck_id}}' from '{{item.ticker_id}}{{item.rundeck_id}}' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:09:47,932 :  Error: Could not parse the remainder: '{{item.ticker_id' from '{{item.ticker_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:10:08,544 :  Error: Reverse for 'abort' with arguments '(209, 925)' not found. 1 pattern(s) tried: ['ticker/abort/(?P<id>[^/]+)$'] from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:10:59,636 :  Error: Could not parse the remainder: '&item.rundeck_id' from 'item.ticker_id&item.rundeck_id' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:12:04,328 :  Error: Could not parse the remainder: '&'item.rundeck_id'' from ''item.ticker_id'&'item.rundeck_id'' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:12:04,989 :  Error: Could not parse the remainder: '&'item.rundeck_id'' from ''item.ticker_id'&'item.rundeck_id'' from function detail in line no. 329 (FILENAME views)
ERROR 2022-09-12 17:15:43,698 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-12 17:37:10,249 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-12 18:08:41,690 :  'time_interval' from function initial_data in line no. 40 (FILENAME rundecklog)
ERROR 2022-09-14 15:25:44,035 :  Expecting property name enclosed in double quotes: line 7 column 3 (char 63) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:35:42,551 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:36:33,665 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:36:53,411 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:38:04,929 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:38:49,240 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:38:51,020 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:40:27,150 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:40:27,584 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:43:07,701 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:43:07,712 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:44:17,602 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:44:18,468 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:45:30,813 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:48:10,351 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:48:10,352 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:51:17,746 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:51:29,065 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:52:09,994 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:53:08,226 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 15:58:16,141 :  Expecting property name enclosed in double quotes: line 2 column 4 (char 5) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 16:26:53,441 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1586 (FILENAME views)
ERROR 2022-09-14 16:31:10,836 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:31:14,295 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:31:14,965 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:31:15,645 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:31:16,255 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:36:23,868 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:38:01,848 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:38:17,054 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:40:13,523 :  'newTickerPriority' from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:40:44,667 :  Expecting value: line 1 column 2 (char 1) from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:42:10,276 :  'newTickerPriority' from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:42:51,590 :  'newTickerPriority' from function closeTicker in line no. 1588 (FILENAME views)
ERROR 2022-09-14 16:46:05,298 :  Reverse for 'unknownControllerRemove' not found. 'unknownControllerRemove' is not a valid view function or pattern name. from function createTicker in line no. 249 (FILENAME views)
ERROR 2022-09-14 16:46:07,690 :  Reverse for 'unknownControllerRemove' not found. 'unknownControllerRemove' is not a valid view function or pattern name. from function createTicker in line no. 249 (FILENAME views)
ERROR 2022-09-14 17:22:46,141 :  Expecting value: line 7 column 14 (char 135) from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:23:40,821 :  can only concatenate str (not "datetime.timedelta") to str from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:23:59,294 :  unsupported type for timedelta minutes component: str from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:26:05,790 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 393 (FILENAME gadget)
ERROR 2022-09-14 17:37:04,914 :  can only concatenate str (not "datetime.timedelta") to str from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:40:24,246 :  can only concatenate str (not "datetime.timedelta") to str from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:41:16,257 :  can only concatenate str (not "datetime.timedelta") to str from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:41:51,103 :  can only concatenate str (not "datetime.timedelta") to str from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:46:42,446 :  'str' object has no attribute 'strftime' from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:47:14,282 :  'str' object has no attribute 'strptime' from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 17:48:43,059 :  'str' object has no attribute 'strptime' from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 18:05:38,905 :  unconverted data remains: :24.000000 from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 18:05:51,869 :  unconverted data remains: :24 from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 18:49:50,257 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 393 (FILENAME gadget)
ERROR 2022-09-14 18:50:17,372 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 393 (FILENAME gadget)
ERROR 2022-09-14 18:51:25,580 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 393 (FILENAME gadget)
ERROR 2022-09-14 18:54:36,306 :  name 'start_time' is not defined from function checkPriorityTicker in line no. 1476 (FILENAME views)
ERROR 2022-09-14 19:01:52,706 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 393 (FILENAME gadget)
ERROR 2022-09-14 19:02:22,561 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 393 (FILENAME gadget)
ERROR 2022-09-14 19:06:57,710 :  QuerySet indices must be integers or slices, not str. from function configApi in line no. 816 (FILENAME views)
ERROR 2022-09-14 19:07:18,396 :  get() returned more than one TickerHistory -- it returned 2! from function configApi in line no. 816 (FILENAME views)
ERROR 2022-09-14 19:35:38,520 :  Expecting property name enclosed in double quotes: line 2 column 9 (char 10) from function checkPriorityTicker in line no. 1478 (FILENAME views)
ERROR 2022-09-14 19:37:27,300 :  Expecting property name enclosed in double quotes: line 2 column 9 (char 10) from function checkPriorityTicker in line no. 1478 (FILENAME views)
ERROR 2022-09-14 19:38:06,910 :  Expecting property name enclosed in double quotes: line 2 column 9 (char 10) from function checkPriorityTicker in line no. 1478 (FILENAME views)
ERROR 2022-09-15 13:58:15,936 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:58:25,484 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:58:27,162 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:58:29,438 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:58:59,420 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:59:15,219 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:59:22,921 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:59:24,192 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 13:59:25,785 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 14:00:00,538 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1500 (FILENAME views)
ERROR 2022-09-15 14:38:50,810 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 14:58:04,782 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 15:00:06,472 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 15:02:44,687 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 15:12:11,522 :  'Request' object has no attribute 'header' from function checkPriorityTicker in line no. 1498 (FILENAME views)
ERROR 2022-09-15 16:20:59,624 :  'bytes' object has no attribute 'get' from function checkPriorityTicker in line no. 1497 (FILENAME views)
ERROR 2022-09-15 16:25:14,398 :  'bytes' object has no attribute 'get' from function checkPriorityTicker in line no. 1497 (FILENAME views)
ERROR 2022-09-15 16:25:19,450 :  'bytes' object has no attribute 'get' from function checkPriorityTicker in line no. 1497 (FILENAME views)
ERROR 2022-09-15 16:29:05,896 :  'Request' object has no attribute 'bodyData' from function checkPriorityTicker in line no. 1498 (FILENAME views)
ERROR 2022-09-15 16:29:18,043 :  Unable to update: 'emergencySelecter' from function datagetter in line no. 427 (FILENAME gadget)
ERROR 2022-09-15 16:30:17,282 :  'Request' object has no attribute 'bodyData' from function checkPriorityTicker in line no. 1498 (FILENAME views)
ERROR 2022-09-15 16:34:51,183 :  string indices must be integers from function checkPriorityTicker in line no. 1498 (FILENAME views)
ERROR 2022-09-15 16:40:21,231 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 16:40:54,756 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 16:41:21,837 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 16:42:11,788 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 17:10:14,535 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 17:12:15,437 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 17:13:01,572 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 17:13:52,965 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 17:14:46,241 :  string indices must be integers from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-09-15 17:16:16,131 :  'tickerToken' from function checkPriorityTicker in line no. 1499 (FILENAME views)
ERROR 2022-10-03 12:39:35,565 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 419 (FILENAME gadget)
ERROR 2022-10-03 15:14:43,137 :  Invalid block tag on line 19: 'endblock'. Did you forget to register or load this tag? from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:14:46,219 :  Invalid block tag on line 19: 'endblock'. Did you forget to register or load this tag? from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:22:07,519 :  Reverse for 'sysLog' not found. 'sysLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:48:14,123 :  Reverse for 'celeryBeatLog' not found. 'celeryBeatLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:50:18,564 :  Reverse for 'celeryBeatLog' not found. 'celeryBeatLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:51:47,620 :  Reverse for 'celeryBeatLog' not found. 'celeryBeatLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:52:59,276 :  Reverse for 'celeryBeatLog' not found. 'celeryBeatLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:53:06,387 :  Reverse for 'celeryWorkerLog' not found. 'celeryWorkerLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:55:34,029 :  Reverse for 'celeryWorkerLog' not found. 'celeryWorkerLog' is not a valid view function or pattern name. from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 15:59:09,646 :  Invalid block tag on line 242: 'endblock'. Did you forget to register or load this tag? from function systemLog in line no. 1639 (FILENAME views)
ERROR 2022-10-03 19:23:11,195 :  Unable to update: (1406, "Data too long for column 'rooms' at row 1") from function datagetter in line no. 435 (FILENAME gadget)
ERROR 2022-10-03 19:23:20,708 :  Unable to update: get() returned more than one TickerDetails -- it returned 2! from function datagetter in line no. 435 (FILENAME gadget)
ERROR 2022-10-04 15:17:09,338 :  Unable to update: get() returned more than one TickerDetails -- it returned 2! from function datagetter in line no. 435 (FILENAME gadget)
ERROR 2022-10-04 15:17:09,438 :  Unable to update: get() returned more than one TickerDetails -- it returned 2! from function datagetter in line no. 435 (FILENAME gadget)
ERROR 2022-10-04 15:29:00,256 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 419 (FILENAME gadget)
ERROR 2022-10-04 15:30:31,281 :  Exception while insertion: time data '' does not match format '%Y-%m-%dT%H:%M' from function datagetter in line no. 419 (FILENAME gadget)
ERROR 2022-10-04 15:47:46,871 :  Error: 'function' object has no attribute 'apply_async' from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-10-04 15:48:28,749 :  Error: 'function' object has no attribute 'apply_async' from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-10-04 15:48:32,692 :  Error: 'function' object has no attribute 'apply_async' from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-10-06 12:02:23,869 :  'runningTicker' from function checkPriorityTicker in line no. 1469 (FILENAME views)
ERROR 2022-10-06 12:06:50,329 :  'runningTicker' from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-06 12:10:54,846 :  get expected at least 1 argument, got 0 from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-06 12:24:41,191 :  get expected at least 1 argument, got 0 from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-06 12:26:03,905 :  get expected at least 1 argument, got 0 from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-06 12:27:11,566 :  'int' object is not subscriptable from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-06 12:27:58,161 :  'int' object is not subscriptable from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-06 12:32:34,180 :  'runningTickerID' from function checkPriorityTicker in line no. 1465 (FILENAME views)
ERROR 2022-10-07 11:55:00,010 :  Ticker id not found from function callscheduledticker in line no. 24 (FILENAME tasks)
ERROR 2022-10-07 14:46:26,586 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-10-11 17:46:30,337 :  Ticker id not found from function callscheduledticker in line no. 24 (FILENAME tasks)
ERROR 2022-10-11 17:46:30,337 :  Ticker id not found from function callscheduledticker in line no. 24 (FILENAME tasks)
ERROR 2022-10-12 19:25:04,178 :  Ticker id not found from function callscheduledticker in line no. 24 (FILENAME tasks)
ERROR 2023-01-19 14:00:25,043 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9251b310d0>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-19 14:00:25,044 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9251b310d0>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-19 14:00:33,235 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f925069e640>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-19 14:00:33,236 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f925069e640>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-19 18:40:51,412 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9251183640>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-19 18:40:51,413 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9251183640>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-19 18:40:53,459 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9250eb5070>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-19 18:40:53,460 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f9250eb5070>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-19 18:59:41,914 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f92517ca5e0>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-19 18:59:41,923 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f92517ca5e0>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-20 14:26:00,020 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb951bdc880>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-20 14:26:00,020 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb951bdc880>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-20 14:29:47,347 :  Api call error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb952427b50>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 595 (FILENAME views)
ERROR 2023-01-20 14:29:47,349 :  Error: HTTPSConnectionPool(host='dvs-uatblue.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb952427b50>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2023-01-20 17:29:00,016 :  Ticker id not found from function callscheduledticker in line no. 24 (FILENAME tasks)
